export type ProductionTool = {
  id: string;
  name: string;
  category: string;
  cost: string;
  fit: string;
  why: string;
  url: string;
};

export const productionTools: ProductionTool[] = [
  {
    id: "spark-lists",
    name: "Spark Lists",
    category: "AI",
    cost: "Free",
    fit: "AI playlist from a seed track",
    why: "Non-Stop Spark’s playlist builder. Seed a vault cut, pull neighbours, then pitch on Promotion.",
    url: "/spark",
  },
  {
    id: "spark-atlas",
    name: "Spark Atlas",
    category: "AI",
    cost: "Free",
    fit: "Artist neighbourhood map",
    why: "See who sits next to a Dutcheyy artist. Use closer names for playlists, blogs, and sync tags.",
    url: "/spark",
  },
  {
    id: "vital",
    name: "Vital",
    category: "Synths",
    cost: "Free / paid skins",
    fit: "Leads, bass, FX without a licence wall",
    why: "Wavetable engine close to Serum’s workflow. Start here if the vault needs more original tones.",
    url: "https://vital.audio/",
  },
  {
    id: "komplete",
    name: "Native Instruments Komplete",
    category: "Synths",
    cost: "Paid (Native Access)",
    fit: "Battery, Massive X, Kontakt, Super 8, Reaktor, Guitar Rig",
    why: "Use the Logic + Native Instruments recipe in this suite. Licence through Native Access.",
    url: "https://www.native-instruments.com/en/products/komplete/bundles/komplete-15/",
  },
  {
    id: "serum",
    name: "Xfer Serum 2",
    category: "Synths",
    cost: "Paid",
    fit: "EDM / house / bass design",
    why: "Still the session language for electronic records. Huge preset and tutorial ecosystem.",
    url: "https://xferrecords.com/products/serum-2",
  },
  {
    id: "diva",
    name: "u-he Diva",
    category: "Synths",
    cost: "Paid",
    fit: "Warm analog-style pads and trance lines",
    why: "Gives body when Serum/Vital get too digital. Good contrast for dark driving cuts.",
    url: "https://u-he.com/products/diva/",
  },
  {
    id: "logic",
    name: "Logic Pro",
    category: "DAW",
    cost: "Paid (Mac App Store)",
    fit: "Stock mixer + template in this suite",
    why: "Channel EQ, Compressor, Space Designer, ChromaGlow, Multimeter. Use the Dutcheyy EDM mix template on this page.",
    url: "https://www.apple.com/logic-pro/",
  },
  {
    id: "waves",
    name: "Waves Creative Access / plugins",
    category: "Mix",
    cost: "Sub or perpetual",
    fit: "SSL, C6, CLA, H-Delay, L2 on the Logic template",
    why: "Colour and glue on drums, vocals and mixbus. Licence via Waves Central — no cracked copies.",
    url: "https://www.waves.com/",
  },
  {
    id: "ableton",
    name: "Ableton Live",
    category: "DAW",
    cost: "Paid (Intro → Suite)",
    fit: "Arrangement, clips, live performance",
    why: "Fast for electronic structure, warping, and session-view ideas that become catalogue tracks.",
    url: "https://www.ableton.com/en/live/",
  },
  {
    id: "fl",
    name: "FL Studio",
    category: "DAW",
    cost: "Paid, lifetime updates",
    fit: "Pattern-based EDM writing",
    why: "Piano roll and lifetime upgrades. Strong if you already sketch in FL.",
    url: "https://www.image-line.com/fl-studio/",
  },
  {
    id: "proq",
    name: "FabFilter Pro-Q",
    category: "Mix",
    cost: "Paid",
    fit: "Surgical EQ on dense synth stacks",
    why: "Dynamic EQ and masking visualisation. Core for kick vs bass vs lead collisions.",
    url: "https://www.fabfilter.com/products/pro-q-4-equalizer-plug-in",
  },
  {
    id: "prol",
    name: "FabFilter Pro-L",
    category: "Mix",
    cost: "Paid",
    fit: "Transparent limiting before a master",
    why: "True-peak control so Amuse deliveries do not clip on DSPs.",
    url: "https://www.fabfilter.com/products/pro-l-2-limiter-plug-in",
  },
  {
    id: "neutron",
    name: "iZotope Neutron",
    category: "Mix",
    cost: "Paid",
    fit: "Masking and first-pass balances",
    why: "Assistant mode is a second pair of ears on layered EDM sessions, then you override.",
    url: "https://www.izotope.com/en/products/neutron.html",
  },
  {
    id: "span",
    name: "Voxengo SPAN",
    category: "Mix",
    cost: "Free",
    fit: "Spectrum check",
    why: "See mud and harshness instead of guessing. Put it on the master while you mix.",
    url: "https://www.voxengo.com/product/span/",
  },
  {
    id: "youlean",
    name: "Youlean Loudness Meter",
    category: "Mastering",
    cost: "Free / Pro",
    fit: "LUFS and true peak for streaming",
    why: "Check integrated loudness before you send to Amuse. Platforms will normalise anyway.",
    url: "https://youlean.co/youlean-loudness-meter/",
  },
  {
    id: "ozone",
    name: "iZotope Ozone",
    category: "Mastering",
    cost: "Paid",
    fit: "Release-ready masters and references",
    why: "Maximizer + assistant for Spotify/Apple-style loudness. Still get a human master for festival / vinyl.",
    url: "https://www.izotope.com/en/products/ozone.html",
  },
  {
    id: "smartlimit",
    name: "sonible smart:limit",
    category: "Mastering",
    cost: "Paid",
    fit: "Club + streaming loudness with quality hints",
    why: "Helps stop over-limiting that dies after DSP normalisation.",
    url: "https://www.sonible.com/smartlimit/",
  },
  {
    id: "smarteq",
    name: "sonible smart:EQ",
    category: "Mix",
    cost: "Paid",
    fit: "Unmasking competing synths",
    why: "Adaptive EQ across tracks when the arrangement is dense.",
    url: "https://www.sonible.com/smarteq4/",
  },
  {
    id: "splice",
    name: "Splice",
    category: "Sound",
    cost: "Credits / sub",
    fit: "One-shots, loops, presets",
    why: "Faster than hunting folders. Tag samples you actually clear for sync.",
    url: "https://splice.com/",
  },
  {
    id: "soundid",
    name: "Sonarworks SoundID Reference",
    category: "Monitoring",
    cost: "Paid",
    fit: "Headphone / speaker correction",
    why: "Stops mixing for a coloured room. Translation is the cheapest way to sound “pro”.",
    url: "https://www.sonarworks.com/soundid-reference",
  },
  {
    id: "metricab",
    name: "ADPTR Metric AB",
    category: "Monitoring",
    cost: "Paid",
    fit: "A/B against commercial references",
    why: "Drop a Trap Nation / Beatport reference and match tone, width, and loudness honestly.",
    url: "https://www.plugin-alliance.com/en/products/adptr_metricab.html",
  },
  {
    id: "rx",
    name: "iZotope RX",
    category: "Repair",
    cost: "Paid",
    fit: "Clicks, noise, vocal salvage",
    why: "Saves vocal chops and field recordings before they go to libraries.",
    url: "https://www.izotope.com/en/products/rx.html",
  },
  {
    id: "lalal",
    name: "Lalal.ai",
    category: "Repair",
    cost: "Pay per stem",
    fit: "Stem split for remixes and repairs",
    why: "Pull vocal / drums / bass from a bounce when you do not have the session.",
    url: "https://www.lalal.ai/",
  },
  {
    id: "soothe",
    name: "oeksound soothe2",
    category: "Mix",
    cost: "Paid",
    fit: "Resonance taming on vocals and synths",
    why: "Kills harsh 2–8 kHz without a dull mix. High impact on dark + vocal EDM.",
    url: "https://oeksound.com/plugins/soothe2/",
  },
  {
    id: "valhalla",
    name: "Valhalla SuperMassive",
    category: "FX",
    cost: "Free",
    fit: "Huge spaces and transitions",
    why: "Free cinematic verbs/delays for risers and breakdowns.",
    url: "https://valhalladsp.com/shop/reverb/valhalla-supermassive/",
  },
  {
    id: "tdrnova",
    name: "Tokyo Dawn TDR Nova",
    category: "Mix",
    cost: "Free / Gentleman’s",
    fit: "Dynamic EQ on the cheap",
    why: "Free alternative while you save for Pro-Q.",
    url: "https://www.tokyodawn.net/tdr-nova/",
  },
  {
    id: "audiomovers",
    name: "Audiomovers ListenTo",
    category: "Collab",
    cost: "Sub",
    fit: "High-quality remote playback",
    why: "Send mixes to features, mixers, or radio without WhatsApp compression.",
    url: "https://audiomovers.com/",
  },
];

export const productionCategories = [...new Set(productionTools.map((tool) => tool.category))];
