import type { RadioStation } from "./types";
import { slugId } from "./ids";

const extras: Array<Partial<RadioStation> & { name: string }> = [
  { name: "BBC Radio Scotland", website: "https://www.bbc.co.uk/radioscotland", email: "", phone: "", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "BBC Radio nan Gàidheal", website: "https://www.bbc.co.uk/radionangaidheal", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "BBC Radio Orkney", website: "https://www.bbc.co.uk/radiorkney", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "BBC Radio Shetland", website: "https://www.bbc.co.uk/radioshetland", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "BBC Introducing in Scotland", website: "https://www.bbc.co.uk/introducing", submissionPage: "https://www.bbc.co.uk/introducing/uploader", source: "https://www.bbc.co.uk/introducing" },
  { name: "Capital Scotland", website: "https://www.capitalfm.com/scotland/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Heart Scotland", website: "https://www.heart.co.uk/scotland/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Smooth Radio Scotland", website: "https://www.smoothradio.com/scotland/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Nation Radio Scotland", website: "https://nationradio.scot/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "GO Radio", website: "https://www.thisisgo.co.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "STV Radio", website: "https://www.stv.tv/radio", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Clyde 1", website: "https://www.clyde1.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Forth 1", website: "https://www.forthone.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Northsound 1", website: "https://www.northsound1.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Moray Firth Radio (MFR)", website: "https://www.mfr.co.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Tay FM", website: "https://www.tayfm.co.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Original 106 Aberdeen", website: "https://original106.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Central FM", website: "https://www.centralfm.co.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Greatest Hits Radio Glasgow & The West", website: "https://planetradio.co.uk/greatest-hits/glasgow/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "SIBC Shetland", website: "https://www.sibc.co.uk/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Isles FM", website: "https://www.islesfm.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Radio Skye", website: "https://www.radioskye.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Radio Wester Ross", website: "https://www.radiowesterross.com/", source: "https://en.wikipedia.org/wiki/Template:Radio_in_Scotland" },
  { name: "Nevis Radio", website: "https://www.nevisradio.co.uk/", email: "david@nevisradio.co.uk", phone: "01397 700007", source: "https://www.nevisradio.co.uk/" },
  { name: "Celtic Music Radio", website: "https://celticmusicradio.net/", source: "https://celticmusicradio.net/" },
  { name: "Awaz FM", website: "https://www.awazfm.co.uk/", source: "https://www.awazfm.co.uk/" },
  { name: "shmuFM", website: "https://www.shmu.org.uk/radio", source: "https://www.shmu.org.uk/radio" },
  { name: "Irvine Beat FM", website: "https://www.irvinebeatfm.com/", source: "https://www.irvinebeatfm.com/" },
  { name: "Deveron FM", website: "https://www.deveronfm.co.uk/", email: "lynn@deveronfm.co.uk", phone: "01261 812000", source: "https://www.deveronfm.co.uk/" },
  { name: "TD1 Radio", website: "https://www.td1radio.scot/", email: "info@td1radio.scot", phone: "01896 888 111", source: "https://www.td1radio.scot/" },
  { name: "Heartland FM", website: "https://www.heartlandfm.co.uk/", source: "https://www.heartlandfm.co.uk/" },
  { name: "Bute FM", website: "https://www.butefm.com/", source: "https://www.butefm.com/" },
  { name: "Mearns FM", website: "https://www.mearnsfm.org.uk/", source: "https://www.mearnsfm.org.uk/" },
  { name: "Subcity Radio", website: "https://subcity.org/", source: "https://subcity.org/" },
  { name: "Fresh Air Edinburgh", website: "https://freshair.org.uk/", source: "https://freshair.org.uk/" },
  { name: "Black Diamond FM", website: "https://www.blackdiamondfm.com/", source: "https://www.blackdiamondfm.com/" },
  { name: "Sunny Govan Radio", website: "https://www.sunnygovan.com/", source: "https://www.sunnygovan.com/" },
  { name: "Two Lochs Radio", website: "https://www.twolochsradio.co.uk/", source: "https://www.twolochsradio.co.uk/" },
  { name: "Cuillin FM", website: "https://www.cuillinfm.co.uk/", source: "https://www.cuillinfm.co.uk/" },
  { name: "Oban FM", website: "https://www.obanfm.org.uk/", source: "https://www.obanfm.org.uk/" },
];

export function extraScottishStations(): RadioStation[] {
  return extras.map((item, i) => ({
    id: slugId("radio-sco", item.name, i),
    name: item.name,
    country: "Scotland, United Kingdom",
    stationType: "Scottish radio",
    verification: "Web scout 2026",
    genreFit: "Local / national Scotland — confirm show fit",
    website: item.website || "",
    submissionPage: item.submissionPage || item.website || "",
    contact: item.email || item.phone || "",
    email: item.email || "",
    phone: item.phone || "",
    submissionFormat: "Check station website",
    accepting: "Research required",
    priority: "High",
    status: "scouted",
    notes: "Added from public Scottish radio directories. Confirm current music policy before pitching.",
    source: item.source || "",
  }));
}
